import {
  ArrowUpRight,
  Bell,
  BellRing,
  BookOpen,
  Briefcase,
  BriefcaseBusiness,
  CalendarClock,
  CalendarDays,
  Camera,
  Compass,
  FileText,
  Gavel,
  Globe,
  GraduationCap,
  Handshake,
  HeartHandshake,
  HeartPulse,
  Landmark,
  Library,
  LifeBuoy,
  Lightbulb,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquareWarning,
  Mic,
  Newspaper,
  NotebookPen,
  PartyPopper,
  Presentation,
  Scale,
  ScrollText,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Star,
  Ticket,
  Trophy,
  Users,
  UsersRound,
  Vote,
  type LucideIcon,
} from "lucide-react";

/**
 * Registre des icônes utilisables dans `links.config.ts`.
 * Pour ajouter une icône : l’importer depuis « lucide-react » (https://lucide.dev/icons)
 * puis l’ajouter à cet objet. Le nom devient aussitôt disponible (avec autocomplétion) dans la configuration.
 */
export const icons = {
  ArrowUpRight,
  Bell,
  BellRing,
  BookOpen,
  Briefcase,
  BriefcaseBusiness,
  CalendarClock,
  CalendarDays,
  Camera,
  Compass,
  FileText,
  Gavel,
  Globe,
  GraduationCap,
  Handshake,
  HeartHandshake,
  HeartPulse,
  Landmark,
  Library,
  LifeBuoy,
  Lightbulb,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquareWarning,
  Mic,
  Newspaper,
  NotebookPen,
  PartyPopper,
  Presentation,
  Scale,
  ScrollText,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Star,
  Ticket,
  Trophy,
  Users,
  UsersRound,
  Vote,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function getIcon(name: IconName): LucideIcon {
  return icons[name];
}
